version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    container_name: foodgram_db
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: always

  backend:
    image: peterwi/foodgram_backend
    container_name: foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media
    depends_on:
      - db
    restart: on-failure

  frontend:
    image: peterwi/foodgram_frontend
    container_name: foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend
    restart: no

  gateway:
    image: peterwi/foodgram_gateway
    container_name: foodgram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - media:/media
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    ports:
      - 9000:80
    restart: always