# Generated by Django 3.2.16 on 2023-12-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="time",
            new_name="cooking_time",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="ingredient",
            new_name="ingredients",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="tag",
            new_name="tags",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
