# Generated by Django 3.2.16 on 2024-03-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_auto_20240320_2031"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"verbose_name": "ингредиенты"},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ("name",), "verbose_name": "рецепты"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "теги"},
        ),
    ]
