# Generated by Django 3.2.16 on 2024-03-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_recipe_ingredient',
        ),
    ]
