# Generated by Django 3.2.16 on 2024-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(
                upload_to='recipe_images/', verbose_name='изображение'
            ),
        ),
    ]
