# Generated by Django 3.2.16 on 2024-04-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=300, verbose_name="пароль"),
        ),
    ]
