# Generated by Django 3.2.16 on 2024-04-20 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0028_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        32767, message="Максимальное значение 32767!"
                    ),
                    django.core.validators.MinValueValidator(
                        1, message="Минимальное значение 1!"
                    ),
                ],
                verbose_name="количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Минимальное значение 1!"
                    ),
                    django.core.validators.MaxValueValidator(
                        32767, message="Максимальное значение 32767!"
                    ),
                ],
                verbose_name="время приготовления",
            ),
        ),
    ]
